# Generated by Django 5.2.4 on 2025-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Идентификатор платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
