# Generated by Django 5.2.4 on 2025-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_payment_payment_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(verbose_name="Сумма платежа"),
        ),
    ]
