# Generated by Django 5.2.4 on 2025-07-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите курс",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Видеоурок"),
        ),
    ]
