# Generated by Django 5.2.4 on 2025-08-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Статус подписки"
            ),
        ),
    ]
